import js from '@eslint/js'
import next from 'eslint-config-next'
import tseslint from 'typescript-eslint'

/**
 * Flat config. Next 16 removed `next lint`, so this is run through the ESLint
 * CLI directly (`bun run lint`) — see the version-16 upgrade guide.
 *
 * The rule set is deliberately close to stock: the value here is having the
 * `@next/next` checks actually run, since the codebase already carries
 * `eslint-disable` comments that were suppressing a linter that was never
 * installed.
 *
 * ESLint is held at 9.x — `eslint-plugin-react`, which `eslint-config-next`
 * depends on, calls a context API that 10.x removed and throws on every file.
 */
const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'src/migrations/**',
      // Generated by `bun run generate:types` / `generate:importmap`.
      'src/payload-types.ts',
      'src/app/(payload)/admin/importMap.js',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...next,
  {
    rules: {
      // The Payload config and seed data legitimately carry wide shapes.
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
]

export default config
